# Generated by Django 6.0.4 on 2026-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
